### ISSUE TITLE
Biqu H2

### ISSUE THREAD

**Issue by edombek** [Tombraider2006/klipperFB6#12]
Мне кажется или обновили версию экструдера и теперь она не влазит в крепления под него которые ты приложил? зхоидт с трудом и только с открытой лапкой филамента

**Comment by Tombraider2006** [comment]
вы абсолютно правы и если почитаете более внимательно то увидите что добавлена версия 2VS и приложен архив к нему https://github.com/Tombraider2006/klipperFB6/blob/main/karas/5015v2s.rar

**Comment by edombek** [comment]
А варианта под 4010 улитки нету?
