### ISSUE TITLE
ошибка в статье Автоперезапуск сервиса klipper после включения принтера

### ISSUE THREAD

**Issue by obla4ko** [Tombraider2006/klipperFB6#2]
в статье указано что необходимо набирать команду "udevadm monitor – kernel – property – subsystem-match=usb"
она не выводит нужных параметров, правильная команда "udevadm monitor --kernel --property --subsystem-match=usb"

**Comment by Tombraider2006** [comment]
спасибо за информацию, к сожалению статья не моя и я не  ее автор, я лишь указал ссылку как на интересный ресурс.
