### ISSUE TITLE
UART cable solder

### ISSUE THREAD

**Issue by ColdBeer72** [Tombraider2006/klipperFB6#5]
Hi!
In your page you say it's obsolete to desolder the resistors, but pictures show there is no resistor yet in the board...
I suppose those are pictures with older method used.
Do you mean I could directly solder the cable right in the upper side of the resistors (towards the drivers)?

**Comment by Tombraider2006** [comment]
you god damm right. on pictures old method.

**Comment by ColdBeer72** [comment]
Oh thanks!
So, it's really secure to solder the cable directly in the resistor (driver's side), isn't it?

**Comment by Tombraider2006** [comment]
yes, this has already been tested by several users, everything works. it also eliminates the risk of breaking the track when soldering

**Comment by Tombraider2006** [comment]
be sure to use hot melt adhesive to avoid breaking the wire from vibration during future operation of the printer.

**Comment by Tombraider2006** [comment]
green side of course.

**Comment by ColdBeer72** [comment]
Thanks again for the clarification
