### ISSUE TITLE
Силиконка V6 и хотэнд

### ISSUE THREAD

**Issue by Sinicin1803** [Tombraider2006/klipperFB6#6]
Здравствуйте.
В разделе [Что купить](https://github.com/Tombraider2006/klipperFB6/blob/main/what_2_buy/readme.md) пункт 4 такой текст: "Сейчас проще - покупаем вид v6 [тут](http://alii.pub/6i4618)".
Я, как новичок и не специалист, выбрал именно  V6 ... по приезду посылки выяснилось, что правильней будет "V6 PT100 -Blue" ... 
Прошу подправить этот момент.

А ещё, в первом пункте неплохо было бы хоть в кратце, для начинающих, разъяснить, для чего нужна модернизация/замена хотэнда. Я вот всё не мог понять, почему сопло и горло должны выставляться не так, как на стоковом, для чего эти танцы с бубнами... Пока в чате не поняли суть моего вопроса и не разъяснили. Вот это один из ответов, ну я думаю Вы, как специалист, сможете его правильно оформить.

"Потому что в стоковом не правильно собрана данная часть, производитель для чего то воткнул сопло мк8. Поэтому и горло на стоковом близко к кубику, что не есть хорошо! И трубка тефлоновая до конца проходит в горле, и при высоких температурах сопла, выше 230, данная трубка может оплавиться, что приведет к пробке!"

Я думаю, что у новичков будет меньше дурацких вопросов. Ведь нормальный человек всегда пытается понять, для чего он должен сделать именно так, а не иначе...

З.Ы. Спасибо за Ваши инструкции!

**Comment by Tombraider2006** [comment]
по первому, исправил, по второму, подумаю как оформить нагляднее..
